-- ReliefForge Initial Schema
-- Auto-generated by Prisma, included here for reference

CREATE TABLE "User" (
    "id"         TEXT NOT NULL PRIMARY KEY,
    "email"      TEXT NOT NULL UNIQUE,
    "password"   TEXT NOT NULL,
    "name"       TEXT,
    "usageCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  DATETIME NOT NULL
);

CREATE TABLE "Generation" (
    "id"          TEXT NOT NULL PRIMARY KEY,
    "userId"      TEXT NOT NULL,
    "filename"    TEXT NOT NULL,
    "resolution"  TEXT NOT NULL DEFAULT 'medium',
    "heightScale" REAL NOT NULL DEFAULT 1.0,
    "inverted"    BOOLEAN NOT NULL DEFAULT false,
    "createdAt"   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Generation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
